### ISSUE TITLE
Undefined array key "i18n"

### ISSUE THREAD

**Issue by abm-schuh** [digitalpulsebe/craft-database-translations#1]
I get an error 'Undefined array key "i18n"' when I try to import PHP files from translations-folder.
- vendor/digitalpulsebe/craft-database-translations/src/helpers/PhpTranslationsHelper.php:25
- vendor/digitalpulsebe/craft-database-translations/src/helpers/PhpTranslationsHelper.php:54

It works, when I change those two lines to
$i18n = Craft::$app->getI18n()

My components (Craft::$app->getComponents(false)):

- errorHandler - craft\web\ErrorHandler
- config - craft\services\Config
- db - craft\db\Connection
- path - craft\services\Path
- cache - craft\cache\FileCache
- sites - craft\services\Sites
- request - craft\web\Request
- user - craft\web\User
- log - craft\log\Dispatcher
- updates - craft\services\Updates
- session - craft\web\Session
- users - craft\services\Users
- response - craft\web\Response
- projectConfig - craft\services\ProjectConfig
- plugins - craft\services\Plugins
- view - craft\web\View
- assetManager - craft\web\AssetManager
- mutex - craft\mutex\Mutex
- queue - craft\queue\Queue
- fields - craft\services\Fields
- content - craft\services\Content
- elements - craft\services\Elements
- security - craft\services\Security
- userGroups - craft\services\UserGroups
- webpack - craft\services\Webpack
- locale - craft\i18n\Locale
- utilities - craft\services\Utilities
- volumes - craft\services\Volumes
- gc - craft\services\Gc
- urlManager - craft\web\UrlManager

I tested that import on two projects. It works in one project, but not in the other.

Best regards
Michael

**Comment by jodeba** [comment]
Hi, thank you for your message. I'll have a look at it as soon as possible. What version are you running of the plugin and Craft CMS?

**Comment by abm-schuh** [comment]
Hi, we have Craft Pro 4.7.3 and Database Translations plugin version 2.5.0.
But the second installation where it works has the same version of craft and your plugin.

We had the following code in our config/app.php
I thought it would help to remove it, but we got the same error.

`'components' => [
`        'i18n' => [
`            'translations' => [
`                'contact' => [
`                    'class' => craft\i18n\PhpMessageSource::class,
`                    'sourceLanguage' => 'en-US',
`                    'basePath' => '@translations',
`                    'forceTranslation' => true,
`                ],
`                'customerspecials' => [
`                    'class' => craft\i18n\PhpMessageSource::class,
`                    'sourceLanguage' => 'en-US',
`                    'basePath' => '@translations',
`                    'forceTranslation' => true,
`                ],
`            ],
`        ],
`    ],

**Comment by jodeba** [comment]
Hi, thank you for the information.

I can't reproduce it in Craft 4, but for the Craft 5 branch I had to remove a line "Craft::$app->setComponents", so I tried the same here. Maybe the behaviour changed with a PHP version.

Please update the plugin using:
```
composer require "digitalpulsebe/craft-database-translations:dev-craft-4-develop as 2.5.1"
```

Please let me know if it works, I'll create a release.

**Comment by abm-schuh** [comment]
Thanks. Fixed my problem.

Best regards
Michael

**Comment by jodeba** [comment]
Ok, I made the release.

Have a nice day!
Jonathan
