### ISSUE TITLE
Error: not a correct file type

### ISSUE THREAD

**Issue by HigumaSan4050** [digitalpulsebe/craft-database-translations#2]
When i export translations into a csv file and import this file, i got the error "not a correct file type".

On a Windows machine with Microsoft Excel installed, CSV files may have a MIME type of application/vnd.ms-excel rather than the RFC 4180 suggested type of text/csv.

Error throws in digitalpulsebe\database_translations\controllers\CsvImportController->actionUpload():34

the Uploaded File Object
```
\craft\web\UploadedFile::__set_state(array(
   'name' => 'export_translations-20240221_081548.csv',
   'tempName' => '/home/xxx/code/tmp/phpdGEGhn',
   'type' => 'application/vnd.ms-excel',
   'size' => 1791,
   'error' => 0,
   'fullPath' => 'export_translations-20240221_081548.csv',
   '_tempResource' => NULL,
))
````

Instead of
```
if (empty($uploadedFile) || strpos($uploadedFile->type, 'csv') === false) {
```
use
```
if (empty($uploadedFile) || strpos($uploadedFile->getMimeType(), 'csv') === false) {
````

**Comment by jodeba** [comment]
Hi, great suggestion!

Please update the plugin to 2.5.2 to get this fix.

Thank you!
