### ISSUE TITLE
FR - Integrate with Deepl API

### ISSUE THREAD

**Issue by tigerchick** [digitalpulsebe/craft-database-translations#3]
To piggyback your work on [multi-translator](https://github.com/digitalpulsebe/craft-multi-translator), would it be possible to integrate with the Deepl API to get automatic translations? Could be a killer feature!

**Comment by jodeba** [comment]
Hi @tigerchick ,

this feature is already available.

First select some rows, and the action will appear in the action bar.

![image](https://github.com/digitalpulsebe/craft-database-translations/assets/102023374/1c85ea55-eb9d-4801-b444-51b47b615fb9)

**Comment by tigerchick** [comment]
Amazing! Thank you so much.

**Comment by tigerchick** [comment]
Quick question. Is there a way to map "message" to the default UI language (ie en-GB).
I'd like to bulk translate values that the plugin has identified when rendering templates but the text is displayed in the "Message" column. If I use that column as the source then I get a "Undefined variable $locale" error. I've tried mapping "message" to "en-GB" in the "Map source languages to other languages" setting but that doesn't appear to work.

Is there a faster way to do this other than copy/pasting all the values from the "Message" column to the "en-GB" column (and then using that as source instead)?

**Comment by jodeba** [comment]
Hi,
I think I fixed the issue of "Undefined variable $locale" when you update Multi Translator to 1.5.6.

Another thing you can do is: 
1. take an export (full, or selected rows).
2. In Excel duplicate the message column.
3. Use the import function
4. Map category->category, message->message and the duplicated message column to your default language, ignore the other columns.

But also, if you keep the values empty, they will be rendered in the frontend with the 'message',

**Comment by tigerchick** [comment]
Works brilliantly - thank you
